version: "3.9"

services:
  mysql:
    image: mysql:latest
    container_name: mysql_reporting
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: reporting
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./backup/reporting.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3308:3306"
    networks:
      - superset_network

networks:
  superset_network:
    external: true
